# Generated by Django 4.2.21 on 2025-05-22 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('response_time', '响应时间'), ('api_latency', 'API延迟'), ('resource_usage', '资源使用'), ('error_rate', '错误率'), ('active_users', '活跃用户'), ('cpu_usage', 'CPU使用率'), ('memory_usage', '内存使用率'), ('other', '其他')], max_length=50, verbose_name='指标类型')),
                ('value', models.FloatField(verbose_name='指标值')),
                ('unit', models.CharField(help_text='例如：ms, %, MB', max_length=20, verbose_name='单位')),
                ('related_entity', models.CharField(blank=True, help_text='特定API或资源的标识符', max_length=100, null=True, verbose_name='关联实体')),
                ('context', models.TextField(blank=True, help_text='以JSON格式存储的额外上下文信息', null=True, verbose_name='上下文信息')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
            ],
            options={
                'verbose_name': '性能指标',
                'verbose_name_plural': '性能指标',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type'], name='core_perfor_metric__595368_idx'), models.Index(fields=['related_entity'], name='core_perfor_related_b530ee_idx'), models.Index(fields=['timestamp'], name='core_perfor_timesta_bf12ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='操作的模块，如course, exercise, learning_assistant', max_length=50, verbose_name='模块')),
                ('action', models.CharField(help_text='执行的动作，如view, create, submit', max_length=50, verbose_name='动作')),
                ('details', models.TextField(blank=True, help_text='以JSON格式存储的操作详情', null=True, verbose_name='详细信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, help_text='浏览器和设备信息', null=True, verbose_name='用户代理')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_statistics', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '使用统计',
                'verbose_name_plural': '使用统计',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'action'], name='core_usages_module_c2476e_idx'), models.Index(fields=['user', 'timestamp'], name='core_usages_user_id_4083d6_idx')],
            },
        ),
    ]
