# Generated by Django 4.2.21 on 2025-05-22 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='perf_type_idx',
            old_name='core_perfor_metric__595368_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='perf_entity_idx',
            old_name='core_perfor_related_b530ee_idx',
        ),
        migrations.RenameIndex(
            model_name='performancemetric',
            new_name='perf_time_idx',
            old_name='core_perfor_timesta_bf12ea_idx',
        ),
        migrations.RenameIndex(
            model_name='usagestatistics',
            new_name='usage_mod_act_idx',
            old_name='core_usages_module_c2476e_idx',
        ),
        migrations.RenameIndex(
            model_name='usagestatistics',
            new_name='usage_user_time_idx',
            old_name='core_usages_user_id_4083d6_idx',
        ),
        migrations.AlterField(
            model_name='usagestatistics',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_statistics', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='usagestatistics',
            index=models.Index(fields=['ip_address'], name='usage_ip_idx'),
        ),
    ]
