# Generated by Django 4.2.21 on 2025-05-21 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('fill_blank', '填空题'), ('short_answer', '简答题'), ('coding', '编程题'), ('other', '其他')], default='single_choice', max_length=20, verbose_name='题目类型')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '较简单'), (3, '中等'), (4, '较难'), (5, '困难')], default=3, verbose_name='难度等级')),
                ('answer_template', models.TextField(blank=True, null=True, verbose_name='答案模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.knowledgepoint', verbose_name='关联知识点')),
            ],
            options={
                'verbose_name': '练习题',
                'verbose_name_plural': '练习题',
                'ordering': ['knowledge_point', 'difficulty', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='答案内容')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='反馈')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='courses.exercise', verbose_name='练习题')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生答案',
                'verbose_name_plural': '学生答案',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'exercise')},
            },
        ),
    ]
