# Generated by Django 4.2.21 on 2025-05-22 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_learningrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='learningrecord',
            new_name='lr_stud_course_idx',
            old_name='courses_lea_student_a74868_idx',
        ),
        migrations.RenameIndex(
            model_name='learningrecord',
            new_name='lr_status_idx',
            old_name='courses_lea_status_2e9e5d_idx',
        ),
        migrations.RenameIndex(
            model_name='learningrecord',
            new_name='lr_access_idx',
            old_name='courses_lea_last_ac_f8e3c2_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='courseware',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coursewares', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['subject', 'grade_level'], name='course_subj_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'created_at'], name='course_teacher_date_idx'),
        ),
        migrations.AddIndex(
            model_name='courseware',
            index=models.Index(fields=['course', 'type'], name='cw_course_type_idx'),
        ),
        migrations.AddIndex(
            model_name='courseware',
            index=models.Index(fields=['created_by', 'created_at'], name='cw_creator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['knowledge_point', 'difficulty'], name='ex_kp_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['type'], name='ex_type_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgepoint',
            index=models.Index(fields=['course', 'importance'], name='kp_course_imp_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgepoint',
            index=models.Index(fields=['parent'], name='kp_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecord',
            index=models.Index(fields=['progress'], name='lr_progress_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['student', 'submitted_at'], name='ans_stud_date_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['exercise', 'score'], name='ans_ex_score_idx'),
        ),
    ]
