# Generated by Django 4.2.21 on 2025-07-13 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_rename_courses_lea_student_a74868_idx_lr_stud_course_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('overall_progress', models.FloatField(default=0.0, verbose_name='整体进度百分比')),
                ('required_completed', models.BooleanField(default=False, verbose_name='必修内容是否完成')),
                ('correctness_rate', models.FloatField(default=0.0, verbose_name='练习题正确率')),
                ('total_time_spent', models.PositiveIntegerField(default=0, verbose_name='总学习时间(分钟)')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最近活动时间')),
            ],
            options={
                'verbose_name': '课程进度',
                'verbose_name_plural': '课程进度',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='尝试次数'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='correct_count',
            field=models.PositiveIntegerField(default=0, verbose_name='正确次数'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='是否必做题'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='estimated_time',
            field=models.PositiveIntegerField(default=30, verbose_name='预计学习时间(分钟)'),
        ),
        migrations.AddField(
            model_name='knowledgepoint',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='是否必修'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1, verbose_name='尝试次数'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否正确'),
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.knowledgepoint', verbose_name='父知识点'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_required'], name='ex_required_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgepoint',
            index=models.Index(fields=['is_required'], name='kp_required_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['is_correct'], name='ans_correct_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['student', 'is_correct'], name='ans_stud_correct_idx'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['student', 'course'], name='cp_stud_course_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['is_completed'], name='cp_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['overall_progress'], name='cp_progress_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseprogress',
            unique_together={('student', 'course')},
        ),
    ]
