# Generated by Django 4.2.21 on 2025-07-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseprogress_exercise_attempt_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursewareFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='coursewares/%Y/%m/', verbose_name='文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '课件文件',
                'verbose_name_plural': '课件文件',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='courseprogress',
            name='cp_stud_course_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseprogress',
            name='cp_completed_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningrecord',
            name='lr_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningrecord',
            name='lr_access_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningrecord',
            name='lr_progress_idx',
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='exercise_attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='练习尝试次数'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='exercise_correct_count',
            field=models.PositiveIntegerField(default=0, verbose_name='练习正确次数'),
        ),
        migrations.AddField(
            model_name='courseware',
            name='has_files',
            field=models.BooleanField(default=False, verbose_name='包含文件'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['student', 'is_completed'], name='cp_stud_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['course', 'is_completed'], name='cp_course_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['required_completed'], name='cp_req_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecord',
            index=models.Index(fields=['student', 'status'], name='lr_stud_status_idx'),
        ),
        migrations.AddIndex(
            model_name='learningrecord',
            index=models.Index(fields=['knowledge_point', 'status'], name='lr_kp_status_idx'),
        ),
        migrations.AddField(
            model_name='coursewarefile',
            name='courseware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.courseware', verbose_name='所属课件'),
        ),
        migrations.AddIndex(
            model_name='coursewarefile',
            index=models.Index(fields=['courseware', 'file_type'], name='cwfile_cw_type_idx'),
        ),
        migrations.AddIndex(
            model_name='coursewarefile',
            index=models.Index(fields=['upload_time'], name='cwfile_upload_time_idx'),
        ),
    ]
