# Generated by Django 4.2.21 on 2025-06-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('url', models.URLField(max_length=255, verbose_name='Webhook URL')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Webhook配置',
                'verbose_name_plural': 'Webhook配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求数据')),
                ('response_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='响应数据')),
                ('status', models.CharField(choices=[('success', '成功'), ('error', '错误'), ('pending', '处理中')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='ai_services.webhookconfig', verbose_name='Webhook配置')),
            ],
            options={
                'verbose_name': 'Webhook调用日志',
                'verbose_name_plural': 'Webhook调用日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
