# Generated by Django 4.2.21 on 2025-05-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_role_name_idx_user_user_role_idx_and_more'),
    ]

    operations = [
    ]
