"""
Django settings for a7 project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+2*)0s+_b-$d*e)!+q0rozaaybq8nhbx!vmcg!#f^&el_g&ebu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 添加允许的主机
ALLOWED_HOSTS = ['DariaJane.pythonanywhere.com','127.0.0.1','localhost','0.0.0.0','*']

# 添加CSRF信任源，添加具体的ngrok URL
CSRF_TRUSTED_ORIGINS = [
    'https://*', 
    'http://*',
    'https://b8d6dd43f441.ngrok-free.app',
    'http://b8d6dd43f441.ngrok-free.app'
]

# CSRF豁免URL配置，符合这些正则表达式的URL将不需要CSRF验证
CSRF_EXEMPT_URLS = [
    r'^api/.*$',  # 豁免所有API路径
    r'^admin/login/.*$',  # 豁免管理员登录路径
    r'^ngrok-.*$',  # 豁免ngrok路径
    r'^/api/login/$',  # 特别豁免登录API
]

# 设置CSRF cookie名称和域，以便前端正确获取
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

# 可选：如果仍有CSRF问题，可以考虑这些设置（不推荐用于生产环境）
# CSRF_COOKIE_SECURE = False
# CSRF_USE_SESSIONS = False
# CSRF_COOKIE_HTTPONLY = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 第三方应用
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',  # 添加django-filter应用
    
    # 本地应用
    'apps.core',
    'users',
    'courses',
    'ai_services',  # 添加AI服务应用
    'marp_service',  # 添加Marp演示服务应用

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS中间件，必须放在CommonMiddleware之前
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # 自定义中间件
    'apps.core.middleware.RequestLoggingMiddleware',  # 请求日志记录中间件
    'users.middleware.jwt_auth_middleware.JWTAuthMiddleware',  # JWT认证中间件 - 已启用
    'apps.core.middleware.RequestProcessorMiddleware',  # 请求处理中间件
]

ROOT_URLCONF = 'a7.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'a7.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT = '/home/DariaJane/A7/static'
STATIC_URL = 'static/'

# Media files (Uploads)
# 配置媒体文件存储路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# 文件存储配置
DEFAULT_FILE_STORAGE = 'courses.storage.CoursewareFileStorage'

# 文件上传配置
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644  # 文件权限
ALLOWED_FILE_TYPES = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/plain',
    'image/png',
    'image/jpeg',
    'image/gif'
]
MAX_FILE_SIZE_MB = 10  # 最大文件大小（MB）

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 自定义用户模型
AUTH_USER_MODEL = 'users.User'

# REST Framework 配置
REST_FRAMEWORK = {
    # 认证类配置
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT令牌认证（恢复）
        'rest_framework.authentication.SessionAuthentication',  # 会话认证（支持浏览器可视化API）
    ),
    
    # 权限类配置
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # 允许任何请求访问，无需认证
    ),
    
    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',  # 使用页码分页
    'PAGE_SIZE': 20,  # 默认每页20条数据
    
    # 渲染器配置 - 定义API输出格式
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # JSON渲染器
        'rest_framework.renderers.BrowsableAPIRenderer',  # 可视化API渲染器
    ],
    
    # 解析器配置 - 定义API输入解析方式
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',  # JSON解析器
        'rest_framework.parsers.FormParser',  # 表单数据解析器
        'rest_framework.parsers.MultiPartParser',  # 多部分表单数据解析器，支持文件上传
    ],
    
    # 异常处理配置
    'EXCEPTION_HANDLER': 'ai_services.api_response.custom_exception_handler',  # 使用自定义异常处理器
    
    # 过滤配置
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # Django过滤器后端
        'rest_framework.filters.SearchFilter',  # 搜索过滤
        'rest_framework.filters.OrderingFilter',  # 排序过滤
    ],
    
    # 版本控制配置
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',  # 使用URL命名空间进行版本控制
    
    # JSON格式配置
    'COMPACT_JSON': True,  # 压缩JSON以减少响应大小
    
    # 时间格式配置
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',  # 日期时间格式
    'DATE_FORMAT': '%Y-%m-%d',  # 日期格式
    
    # 测试配置
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',  # 测试客户端默认使用JSON格式
    
    # 添加URL方案配置，优先使用HTTPS
    'URL_FORMAT_OVERRIDE': 'format',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'URL_FIELD_NAME': 'url',
    'URL_SCHEME': 'https', 
}

# JWT 配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS 配置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://glowing-sunburst-d86f36.netlify.app",
    "http://glowing-sunburst-d86f36.netlify.app",
    "http://12e11e70c836.ngrok-free.app",
    "https://12e11e70c836.ngrok-free.app",
    "https://046db807ed8b.ngrok-free.app",
    "http://046db807ed8b.ngrok-free.app"
]
CORS_ALLOW_ALL_ORIGINS = True  # 注释掉，改用明确的域名列表

# 修复CORS问题的额外设置
CORS_ALLOW_CREDENTIALS = True  # 允许跨域请求携带凭证
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken', 'Authorization']  # 允许前端访问的响应头

# 预检请求缓存时间设置
CORS_PREFLIGHT_MAX_AGE = 86400  # 预检请求结果缓存1天（86400秒）

# 确保包含指定域名
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://\w+\.ngrok-free\.app$",
    r"^https://glowing-sunburst-d86f36\.netlify\.app$",
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
    r"^https?://.*\.loca\.lt$",  # 允许所有loca.lt子域名
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]

# Swagger/OpenAPI 配置
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
    'VALIDATOR_URL': None,
    # 添加Swagger UI的HTTPS支持
    'SCHEME': 'https',
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch',
        'options',
        'head'
    ],
}

# 启用代理协议头处理，确保ngrok HTTPS请求正确处理
USE_X_FORWARDED_PROTO = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 确保Django生成的URL使用HTTPS
SECURE_SSL_REDIRECT = False  # 在开发环境中设为False，生产环境可设为True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR.parent / 'permission.log'),
            'formatter': 'verbose',
        },
        'jwt_auth_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR.parent / 'jwt_auth.log'),
            'formatter': 'verbose',
        },
        'request_log_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR.parent / 'request.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'permission_log': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'jwt_auth': {
            'handlers': ['jwt_auth_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'request_log': {
            'handlers': ['request_log_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'request_processor': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_services': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },

}

# 中间件配置项
# JWT认证中间件配置
CUSTOM_JWT_ERROR_RESPONSE = True  # 是否使用自定义JWT错误响应

# 请求日志中间件配置
REQUEST_LOG_LEVEL = 'INFO'  # 日志级别：DEBUG, INFO, WARNING, ERROR
LOG_REQUEST_BODY = False  # 是否记录请求体（默认不记录，避免记录敏感信息）
MAX_BODY_LOG_LENGTH = 1000  # 请求体最大记录长度
REQUEST_LOG_EXCLUDE_PATHS = [
    '/admin/jsi18n/',
    '/static/',
    '/media/',
    '/health-check/',
]  # 不记录日志的URL路径

# 请求处理中间件配置
MAX_REQUEST_SIZE = 10 * 1024 * 1024  # 最大请求大小（10MB）
STANDARDIZE_API_RESPONSE = True  # 是否标准化API响应
API_EXTRA_HEADERS = {
    'X-API-Version': '1.0',
    'X-Content-Type-Options': 'nosniff',
}  # 额外响应头
PROCESSOR_EXCLUDE_PATHS = [
    '/admin/',
    '/static/',
    '/media/',
]  # 不进行处理的URL路径

# 角色权限中间件配置
CUSTOM_PERMISSION_DENIED_RESPONSE = True  # 是否使用自定义权限拒绝响应

# n8n Webhook配置
N8N_WEBHOOK_URL = "http://localhost:5678/webhook/bf4dd093-bb02-472c-9454-7ab9af97bd1d"  # 直接设置URL，不从环境变量获取
N8N_WEBHOOK_HEADERS = {
    'Authorization': os.environ.get('N8N_WEBHOOK_AUTH_TOKEN', ''),
    'Content-Type': 'application/json',
}

# Aiohttp配置
AIOHTTP_CLIENT_TIMEOUT = int(os.environ.get('AIOHTTP_CLIENT_TIMEOUT', 30))  # 30秒默认超时

# Marp CLI配置
MARP_CLI_PATH = "marp"

# Marp临时文件配置
MARP_TEMP_DIR = os.path.join(BASE_DIR, 'tmp', 'marp')
